use assets_manager::*;
use std::sync::*;

/// A handle to a asset so that one can be shared by multiple entities. "Static"
/// assets are loaded from a file on the disk and are stored in an
/// [`AssetCache`]. "Dynamic" assets are those generated by code at runtime, and
/// are simply stored on the heap and referenced using [`Arc`]s.
pub enum AssetHandle<T: ?Sized> {
    /// A handle to a static asset that is stored in an [`AssetCache`].
    Static(ArcHandle<T>),
    /// A handle to a dynamic asset that is stored on the heap.
    Dynamic(Arc<T>)
}
